[package]
name = "luc-csv"
version = "0.1.0"
authors = ["childhooooo <yumenaut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
encoding_rs = "0.8.22"
chrono = "0.4"